[package]
name = "rgit"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
sha1 = "0.10.6"
flate2 = { version = "1.0.17", features = ["zlib-rs"], default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.148", features = ["preserve_order"] }
similar = "2.7.0"
wincode = { version = "0.5.5", features = ["derive"] }

# [profile.release]
# lto = true
# opt-level = 3
# codegen-units = 1